#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

pkill -x VBoxClient; sleep 1 && VBoxClient-all &
/usr/bin/picom &
source $HOME/.config/polybar/env.sh
$HOME/.config/polybar/launch.sh &
xset r rate 250 25
